baseURL = 'https://player.radio10.fi/'
locale = 'fi-fi'
title = 'Radio 10'

enableRobotsTXT = true

[markup.goldmark.renderer]
unsafe= true

[markup.goldmark.extensions.passthrough]
  enable = true
  [markup.goldmark.extensions.passthrough.delimiters]
    block = [["$$", "$$"]]
    inline = [["$", "$"]]

uglyURLs = false

[minify]
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.html]
        keepWhitespace = false
        keepComments = false
        keepDefaultAttrVals = true
        keepQuotes = false
    [minify.tdewolff.css.2]
        keepCSS2 = false
    [minify.tdewolff.js]
        keepVarNames = false
        precision = 0
        version = 2022
    [minify.tdewolff.json]
        keepNumbers = false
        precision = 0
    [minify.tdewolff.svg]
        keepComments = false
        keepNamespaces = ['', 'x-bind']
        precision = 0
    [minify.tdewolff.xml]
        keepWhitespace = false
